name: Repository Dispatch
uses: peter-evans/repository-dispatch@0e8ca8c8a5ca5e28d25af2c27fc5aa40f16cffca
with:
  token: ${{ secrets.REPO_ACCESS_TOKEN }}
  repository: enejb/complex-submodule-repo
  event-type: update-submodule-project
  client-payload: '{"github": ${{ toJson(github) }}}'
